### ISSUE TITLE
Muoversi Lombardia: deprecation dates

### ISSUE THREAD

**Issue by ioggstream** [teamdigitale/api-openapi-samples#17]
## Task

Define deprecation fields for lispa metadata and e015.
Is that ok? @stefkohub

```
published: 2018-01-01  # data di pubblicazione
deprecated: 2020-12-31 
retired: 2021-03-31
```

**Comment by stefkohub** [comment]
Siamo d'accordo riguardo le date, di seguito una proposta di tutto il paragrafo relativo a lifecycle: 
```
x-lifecycle:
  published: 2018-01-01 # data di pubblicazione
  deprecated: 2020-12-31 # data inizio dismissione
  retired: 2021-03-31 # data termine dismissione
  maturity: proposal|developing|published|deprecated|retired
```
