### ISSUE TITLE
Muoversi lombardia: glossario

### ISSUE THREAD

**Issue by ioggstream** [teamdigitale/api-openapi-samples#18]
@stefkohub.

Le info di glossario non le metterei direttamente qui ma in components.schemas.

Guarda in questo draft come le informazioni di glossario siano indicate sia sulla classe
che per campo.

https://github.com/teamdigitale/api-openapi-samples/blob/master/external-apis/spid-aa.yaml#L109

Un parser può semplicemente ricostruire tutto il gioco leggendo lo yaml e ricavare l'informazione completa e aggiornata.

eg.

```
    Point:
      externalDocs:
         url: URL VERSO IL GLOSSARIO
         x-glossary: true
      description: Un punto sulla mappa. Questo e' definito in un glossario e linkato tramite externalDocs
         oppure potremmo definire un x-glossary a questo livello.
      type: object
      properties:
        label:
          type: string
        type:
          type: string
        x:
          '$ref': '#/components/schemas/Longitudine'
        y:
          '$ref': '#/components/schemas/Latitudine'
      example:
        label: Rogoredo M3
        type: areadifermata
        x: 9.237421
        y: 45.433681

```
