### ISSUE TITLE
Muoversi Lombardia: ambiente sandbox

### ISSUE THREAD

**Issue by ioggstream** [teamdigitale/api-openapi-samples#19]
@stefkohub fai sapere se vi torna svp.

```
servers:
  url: xxx
  x-sandbox: true
  name: Sandbox
```
